export const POPULAR_CATEGORIES = [
  "Digital Marketing Agencies",
  "Plumbers",
  "Real Estate Agents",
  "Law Firms",
  "Dentists",
  "Coffee Shops",
  "Web Development Studios",
  "Interior Designers",
  "Event Planners",
  "Roofing Contractors",
  "Accounting Firms",
  "Fitness Centers",
  "Software Startups",
  "Restaurants",
  "Electricians",
  "Graphic Designers",
  "HVAC Services",
  "Catering Services",
  "Photographers",
  "Chiropractors",
  "Landscaping Services",
  "Boutique Hotels",
  "Car Dealerships",
  "Veterinary Clinics"
];

export const POPULAR_CITIES = [
  "New York, NY",
  "Los Angeles, CA",
  "London, UK",
  "Austin, TX",
  "San Francisco, CA",
  "Toronto, Canada",
  "Sydney, Australia",
  "Chicago, IL",
  "Miami, FL",
  "Berlin, Germany",
  "Seattle, WA",
  "Dubai, UAE",
  "Singapore",
  "Bangalore, India",
  "Paris, France",
  "Tokyo, Japan",
  "Melbourne, Australia",
  "Boston, MA",
  "Vancouver, Canada",
  "Amsterdam, Netherlands",
  "Denver, CO"
];